<?php

use Profile\Config;

Config::init();

$data_translations = [
    "en" => [
        "page__profession" => "Web Developer",
        "page_index__title" => "Professional Web Developer &amp; Portfolio Experience",
        "page_index__seo-title" => "Arturo López | Web Developer | Turning Ideas into Digital Experiences",
        "page_index__seo-description" => "Hello there! I'm Arturo López, a passionate web developer with over a decade of experience crafting innovative applications. From web to mobile and e-commerce solutions, my mission is to turn your ideas into digital realities. Let's have a conversation and elevate your vision! #WebDevelopment #DigitalExperiences",
        "page_profile__title" => "Arturo López - Web Developer | Professional Profile",
        "page_profile__seo-title" => "Arturo López - Web Developer | Digital Visionary | Experience in Travel, Consulting, and More",
        "page_profile__seo-description" => "Explore my journey as a full-stack developer. With expertise in industries like travel and consulting, my technology-driven passion fuels innovative solutions. From Java to Python, I lead with creativity and vision. Let's connect and elevate your projects! #WebDeveloper #DigitalVisionary",
        "page_profile__text--1" => "I bring a wealth of experience as a full-stack developer, spanning industries such as travel, consulting, recruitment, and human resources. My specialization lies in key technologies including Java, Kotlin, JavaScript, PHP, and Python, enabling me to craft robust and versatile solutions for a range of business needs.",
        "page_profile__text--2" => "My entrepreneurial spirit is fueled by an unwavering passion for continuous learning in the realms of programming, technology, and science. My expertise in interface design and user experience is solid, coupled with proficiency in essential tools like Adobe Photoshop. Moreover, I possess a deep understanding of corporate identity and digital marketing strategies, allowing me to provide holistic and impactful solutions in every project.",
        "page_webapp__title" => "Web Applications",
        "page_webapp__seo-title" => "Web Applications",
        "page_webapp__seo-description" => "I develop web applications with the latest technologies, I have experience in the development of web applications with PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, among others.",
        "nav_item__home" => "Home",
        "nav_item__about" => "About",
        "nav_item__services" => "Services",
        "nav_item__contact" => "Contact",
        "nav_item__profile" => "Profile",
        "section_summary__title" => "Hello world! Welcome to my professional profile.",
        "section_summary__text--1" => "I am a full-stack developer with experience in the travel, consulting, recruiting, and human resources industries. I specialize in technologies with languages such as Java, Kotlin, JavaScript, PHP, and Python.",
        "section_summary__text--2" => "I am an entrepreneur who is passionate about learning more about programming, technology, and science. I have a strong knowledge of interface design, user experience, Adobe Photoshop, corporate identity, and digital marketing.",
        "section_work__title" => "Work experience",
        "section_education__title" => "Education",
        "section_skills__title" => "Skills",
        "section_soft_skills__title" => "Soft Skills",
        "section_about__title" => "Turning Ideas into Digital Experiences",
        "section_about__summary" => "Hello there! I'm Arturo López, a passionate web developer with over a decade of experience in crafting cutting-edge applications and digital solutions. My mission is to transform your visions into reality through the magic of code and creativity.",
        "section_about__address" => "Cancún, Quintana Roo, México",
        "section_about__button--contact" => "Contact",
        "section_about__button--profile" => "Profile",
        "section_services__title" => "Services",
        "section_services__item--webapp__title" => "Web Applications",
        "section_services__item--webapp__text--1" => "From real estate platforms to seamless booking experiences, I've brought innovation to diverse industries.",
        "section_services__item--webapp__text--2" => "My technological palette includes PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, and Bootstrap. Discover how we can bring your ideas to life.",
        "section_services__item--webapp__btn" => "See more about web applications",
        "section_services__item--mobile__title" => "Mobile Applications",
        "section_services__item--mobile__text--1" => "The future is mobile, and I can help you conquer it.",
        "section_services__item--mobile__text--2" => "With expertise in Reactive Design, Android Studio, Java, Kotlin, I design mobile applications for Android and iOS that connect with your users wherever they are.",
        "section_services__item--mobile__btn" => "See more about mobile applications",
        "section_services__item--ecommerce__title" => "E-commerce",
        "section_services__item--ecommerce__text--1" => "Take your products and services to the digital world with cutting-edge e-commerce solutions.",
        "section_services__item--ecommerce__text--2" => "From email marketing strategies to secure payment gateways like PayPal, Stripe, and more, I'm here to propel your online business.",
        "section_services__item--ecommerce__btn" => "See more about e-commerce",
        "section_contact__title" => "Let's Connect!",
        "section_contact__description" => "If you're ready to take your ideas to the next level, I'm here to assist you. Let's have a conversation!",
        "section_contact__description--help" => "Let's Talk!",
        "section_contact__message--success" => "Thank you for your message! I will contact you as soon as possible.",
        "section_contact__message--error__empty" => "Please fill out all the required fields of this form, so we can assist you better. Your information is safe with us and will only be used to respond to your inquiry.",
        "section_contact__message--error__csrf" => "An error occurred while sending the form, please reload the page and try again.",
        "section_contact__message--error__language" => "An error occurred while processing the form, please reload the page and try again.",
        "section_contact__message--error__email" => "Please enter a valid email address.",
        "section_contact__message--error__mail" => "An error occurred while sending the form, please send an email to <a href=\"mailto:lgzarturo@gmail.com\">lgzarturo@gmail.com</a>",
        "contact_form__legend" => "Feel free to reach out to me using the contact form below. I'll get back to you as soon as possible.",
        "contact_form__field--subject__value" => "New message from my website lgzarturo.com",
        "contact_form__field--name" => "Name:",
        "contact_form__field--name__placeholder" => "Enter your full name",
        "contact_form__field--phone" => "Phone:",
        "contact_form__field--phone__placeholder" => "Your contact number",
        "contact_form__field--email" => "Email:",
        "contact_form__field--email__placeholder" => "Your email address",
        "contact_form__field--message" => "Message:",
        "contact_form__field--message__placeholder" => "Feel free to share your message here",
        "contact_form__instructions" => "Please fill out all required fields in the form below. Let's connect and bring your ideas to life!",
        "section_profile_contact_cta__title" => "Let's Collaborate!",
        "section_profile_contact_cta__description" => "Ready to dive into your next project. Let's bring your ideas to life and conquer the digital world.",
        "section_profile_contact_cta__link" => "Let's Talk!",
        "contact_form__button--submit" => "Send Message",
        "footer__owner" => "Arturo López - Web Developer",
        "footer__copy" => "&copy; " . date("Y") . " - All rights reserved",
    ],
    "es" => [
        "page__profession" => "Desarrollador Web",
        "page_index__title" => "Desarrollador Web Profesional &amp; Experiencia en Portafolio",
        "page_index__seo-title" => "Arturo López | Desarrollador Web | Transformando Ideas en Experiencias Digitales",
        "page_index__seo-description" => "¡Hola! Soy Arturo López, un apasionado desarrollador web con más de 10 años de experiencia en la creación de aplicaciones innovadoras. Desde aplicaciones web hasta soluciones móviles y e-commerce, mi misión es convertir tus ideas en realidades digitales. ¡Conversemos y llevemos tu visión al siguiente nivel! #DesarrolloWeb #ExperienciasDigitales",
        "page_profile__title" => "Arturo López - Desarrollador Web | Perfil Profesional",
        "page_profile__seo-title" => "Arturo López - Desarrollador Web | Visionario Digital | Experiencia en Viajes, Consultoría y Más",
        "page_profile__seo-description" => "Descubre mi viaje como desarrollador full-stack. Con experiencia en industrias como viajes y consultoría, mi pasión por la tecnología impulsa soluciones innovadoras. Desde Java hasta Python, lidero con creatividad y visión. ¡Conozcámonos y hagamos que tus proyectos despeguen! #DesarrolladorWeb #VisiónDigital",
        "page_profile__text--1" => "Poseo una amplia trayectoria como desarrollador full-stack, abarcando diversos sectores como el de viajes, consultoría, reclutamiento y recursos humanos. Mi enfoque se centra en tecnologías clave como Java, Kotlin, JavaScript, PHP y Python, lo que me permite crear soluciones sólidas y versátiles para una variedad de necesidades empresariales.",
        "page_profile__text--2" => "Mi espíritu emprendedor se nutre de una pasión constante por el aprendizaje en los campos de la programación, la tecnología y la ciencia. Mi conocimiento en diseño de interfaces y experiencia de usuario es sólido, y tengo destreza en herramientas esenciales como Adobe Photoshop. Además, cuento con una profunda comprensión de la identidad corporativa y las estrategias de marketing digital, lo que me permite ofrecer soluciones holísticas y efectivas en cada proyecto.",
        "page_webapp__title" => "Aplicaciones Web",
        "page_webapp__seo-title" => "Aplicaciones Web",
        "page_webapp__seo-description" => "Desarrollo aplicaciones web con las últimas tecnologías, tengo experiencia en el desarrollo de aplicaciones web con PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, entre otros.",
        "nav_item__home" => "Inicio",
        "nav_item__about" => "Sobre mí",
        "nav_item__services" => "Servicios",
        "nav_item__contact" => "Contacto",
        "nav_item__profile" => "Perfil",
        "section_summary__title" => "¡Hola mundo! Bienvenido a mi perfil profesional.",
        "section_summary__text--1" => "Soy desarrollador full-stack con experiencia en las industrias de viajes, consultoría, reclutamiento y recursos humanos. Me especializo en tecnologías con lenguajes como Java, Kotlin, JavaScript, PHP y Python.",
        "section_summary__text--2" => "Soy un emprendedor apasionado por aprender más sobre programación, tecnología y ciencia. Tengo un sólido conocimiento de diseño de interfaces, experiencia de usuario, Adobe Photoshop, identidad corporativa y marketing digital.",
        "section_work__title" => "Experiencia laboral",
        "section_education__title" => "Educación",
        "section_skills__title" => "Habilidades",
        "section_soft_skills__title" => "Habilidades Blandas",
        "section_about__title" => "Convierto Ideas en Experiencias Digitales",
        "section_about__summary" => "¡Hola! Soy Arturo López, un apasionado desarrollador web con más de una década de experiencia en la creación de aplicaciones y soluciones digitales de vanguardia. Mi misión es transformar tus visiones en realidad a través de la magia del código y la creatividad.",
        "section_about__address" => "Cancún, Quintana Roo, México",
        "section_about__button--contact" => "Contacto",
        "section_about__button--profile" => "Perfil",
        "section_services__title" => "Servicios",
        "section_services__item--webapp__title" => "Aplicaciones Web",
        "section_services__item--webapp__text--1" => "Desde plataformas inmobiliarias hasta experiencias de reservaciones en línea, he llevado la innovación a diversas industrias.",
        "section_services__item--webapp__text--2" => "Mi paleta tecnológica incluye PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3 y Bootstrap. Descubre cómo podemos dar vida a tus ideas.",
        "section_services__item--webapp__btn" => "Ver más sobre aplicaciones web",
        "section_services__item--mobile__title" => "Aplicaciones Móviles",
        "section_services__item--mobile__text--1" => "El futuro es móvil, y puedo ayudarte a conquistarlo.",
        "section_services__item--mobile__text--2" => "Con expertise en Responsive Design, Android Studio, Java, Kotlin, diseño aplicaciones móviles para Android e iOS que conectan con tus usuarios dondequiera que estén.",
        "section_services__item--mobile__btn" => "Ver más sobre aplicaciones móviles",
        "section_services__item--ecommerce__title" => "E-commerce",
        "section_services__item--ecommerce__text--1" => "Lleva tus productos y servicios al mundo digital con soluciones de e-commerce de vanguardia.",
        "section_services__item--ecommerce__text--2" => "Desde estrategias de email marketing hasta pasarelas de pago seguras como PayPal, Stripe y más, estoy aquí para impulsar tu negocio en línea.",
        "section_services__item--ecommerce__btn" => "Ver más sobre e-commerce",
        "section_contact__title" => "¡Vamos a Conectar!",
        "section_contact__description" => "Si estás listo para llevar tus ideas al siguiente nivel, estoy aquí para ayudarte. ¡Conversemos!",
        "section_contact__description--help" => "¿Interesado en trabajar conmigo?",
        "section_contact__message--success" => "¡Gracias por tu mensaje! Me pondré en contacto contigo lo antes posible.",
        "section_contact__message--error__empty" => "Por favor, complete todos los campos requeridos de este formulario, para que podamos atenderle mejor. Su información está segura con nosotros y solo se utilizará para responder a su consulta.",
        "section_contact__message--error__csrf" => "Se ha producido un error al enviar el formulario, por favor recarga la página e intenta nuevamente.",
        "section_contact__message--error__language" => "Se ha producido un error al procesar el formulario, por favor recarga la página e intenta nuevamente.",
        "section_contact__message--error__email" => "Por favor, ingrese una dirección de correo electrónico válida.",
        "section_contact__message--error__mail" => "Se ha producido un error al enviar el formulario, por favor envíe un correo electrónico a <a href=\"mailto:lgzarturo@gmail.com\">lgzarturo@gmail.com</a>.",
        "contact_form__legend" => "Envíame un mensaje a través del siguiente formulario y me pondré en contacto contigo lo antes posible.",
        "contact_form__field--subject__value" => "Nuevo mensaje desde mi sitio web lgzarturo.com",
        "contact_form__field--name" => "Nombre:",
        "contact_form__field--name__placeholder" => "Ingresa tu nombre completo",
        "contact_form__field--phone" => "Teléfono:",
        "contact_form__field--phone__placeholder" => "Tu número de teléfono de contacto",
        "contact_form__field--email" => "Correo electrónico:",
        "contact_form__field--email__placeholder" => "Tu dirección de correo electrónico",
        "contact_form__field--message" => "Mensaje:",
        "contact_form__field--message__placeholder" => "Siéntete libre de compartir tu mensaje aquí",
        "contact_form__instructions" => "Por favor, completa todos los campos requeridos en el formulario a continuación. ¡Vamos a conectarnos y dar vida a tus ideas!",
        "contact_form__button--submit" => "Enviar Mensaje",
        "section_profile_contact_cta__title" => "¡Vamos a Trabajar Juntos!",
        "section_profile_contact_cta__description" => "Listo para sumergirme en tu próximo proyecto. Hagamos que tus ideas tomen forma y conquisten el mundo digital.",
        "section_profile_contact_cta__link" => "¡Conversemos!",
        "footer__owner" => "Arturo López - Desarrollador Web",
        "footer__copy" => "&copy; " . date("Y") . " - Todos los derechos reservados",
    ]
];

$works = [
    [
        "title_en" => "Java Software Engineer",
        "title_es" => "Ingeniero de Software Java",
        "company" => "Revenatium",
        "company_url" => "https://revenatium.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2019 - " . date("Y"),
        "description_en" => "Backend development of web applications with Java, Spring Boot. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, among others.",
        "description_es" => "Desarrollo backend de aplicaciones web con Java, Spring Boot. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, entre otros.",
        "technologies" => [
            "Java",
            "Kotlin",
            "Spring Boot",
            "MongoDB",
            "PostgreSQL",
        ],
    ],
    [
        "title_en" => "Software Engineer",
        "title_es" => "Ingeniero de Software",
        "company" => "StarChoice",
        "company_url" => "https://starchoice.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2018 - 2019",
        "description_en" => "Master of crafting complete web applications with Grails, jQuery, and more. I revolutionized recruitment management with efficient solutions.",
        "description_es" => "Maestro en el arte de crear aplicaciones web completas con Grails, jQuery y más. Revolucioné la gestión de reclutamiento con soluciones eficientes.",
        "technologies" => [
            "Grails",
            "Java",
            "MySQL",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Marketing Manager",
        "title_es" => "Gerente de Marketing",
        "company" => "Grupo Argos",
        "company_url" => "https://grupoargos.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2016 - 2019",
        "description_en" => "Beyond code, I shaped corporate identities and successful digital strategies with Mailchimp, RD Station, HTML5, CSS3, and more.",
        "description_es" => "Más allá del código, moldeé identidades corporativas y estrategias digitales exitosas con Mailchimp, RD Station, HTML5, CSS3 y más.",
        "technologies" => [
            "Adobe Photoshop",
            "Adobe Illustrator",
            "Adobe Premiere",
            "HTML5",
            "CSS3",
            "Bootstrap",
            "WordPress",
            "SEO",
        ],
    ],
    [
        "title_en" => "Java Software Engineer",
        "title_es" => "Ingeniero de Software Java",
        "company" => "Grupo Argos",
        "company_url" => "https://grupoargos.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2012 - 2016",
        "description_en" => "Backend development of web applications with Java, Spring Framework, SQL Server, HTML5, CSS3, Bootstrap. Web application for the management of payroll and human resources.",
        "description_es" => "Desarrollo backend de aplicaciones web con Java, Spring Framework, SQL Server, HTML5, CSS3, Bootstrap. Aplicación web para la gestión de nómina y recursos humanos.",
        "technologies" => [
            "Java",
            "Spring Framework",
            "SQL Server",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Java Developer / Webmaster",
        "title_es" => "Desarrollador Java / Webmaster",
        "company" => "Sunset World Hotels & Resorts",
        "company_url" => "https://sunsetworldresorts.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2009 - 2012",
        "description_en" => "Driving smart solutions with Java, Spring Boot, and more. From Booking Engines to CRM, my focus is on making technology work in your favor.",
        "description_es" => "Impulsando soluciones inteligentes con Java, Spring Boot y más. Desde Booking Engines hasta CRM, mi enfoque es hacer que la tecnología trabaje a tu favor.",
        "technologies" => [
            "Java",
            "Play Framework",
            "Oracle",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Php Developer / Technical Support",
        "title_es" => "Desarrollador Php / Soporte Técnico",
        "company" => "Freelance",
        "company_url" => "https://linkedin.com/in/lgzarturo",
        "location" => "Cancún, Quintana Roo",
        "date" => "2005 - 2009",
        "description_en" => "Web design and development for clients. Technical support for computer equipment, installation of operating systems, and software.",
        "description_es" => "Diseño y desarrollo web para clientes. Soporte técnico para equipos de cómputo, instalación de sistemas operativos y software.",
        "technologies" => [
            "Windows",
            "Linux",
            "Microsoft Office",
            "Adobe Suite",
        ],
    ]
];

$education = [
    [
        "title_en" => "Bachelor of Computer Systems Engineering",
        "title_es" => "Ingeniería en Sistemas Computacionales",
        "school" => "ITCancún",
        "school_url" => "https://www.google.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2000 - 2005",
        "description_en" => "From theory to practice: I participated in creating a customer service and reservation portal, leaving my mark with Java technologies and innovative programming approaches.",
        "description_es" => "De la teoría a la práctica: participé en la creación de un portal de atención al cliente y reservas, dejando mi huella con tecnologías Java y enfoques de programación innovadores.",
    ]
];

$skills = [
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Java",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Kotlin",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Groovy &amp; Grails",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Spring Boot",
    ],
    [
        "icon" => "tabler-icon-file-type-php.svg",
        "title" => "PHP",
    ],
    [
        "icon" => "tabler-icon-file-type-php.svg",
        "title" => "Laravel",
    ],
    [
        "icon" => "tabler-icon-brand-javascript.svg",
        "title" => "JavaScript",
    ],
    [
        "icon" => "tabler-icon-brand-typescript.svg",
        "title" => "Typescript",
    ],
    [
        "icon" => "tabler-icon-brand-python.svg",
        "title" => "Python",
    ],
    [
        "icon" => "tabler-icon-brand-django.svg",
        "title" => "Django",
    ],
];

$soft_skills = [
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Teamwork",
        "title_es" => "Trabajo en equipo",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Leadership",
        "title_es" => "Liderazgo",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Communication",
        "title_es" => "Comunicación",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Problem solving",
        "title_es" => "Resolución de problemas",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Creativity",
        "title_es" => "Creatividad",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Adaptability",
        "title_es" => "Adaptabilidad",
    ]
];
