<?php

$data_translations = [
    "en" => [
        "page__profession" => "Web Developer",
        "page_index__title" => "Professional Web Developer &amp; Portfolio Experience",
        "page_index__seo-title" => "Arturo López - Professional Web Developer &amp; Portfolio Experience",
        "page_index__seo-description" => "I am professional web developer, I have experience with PHP, Javascript, Java, Python, among others.",
        "page_profile__title" => "Arturo López - Web Developer | Professional Profile",
        "page_profile__seo-title" => "Arturo López - Web Developer | Professional Profile",
        "page_profile__seo-description" => "My name is Arturo López, I am a full-stack developer with experience in the travel, consulting, recruiting, and human resources industries.",
        "page_profile__text--1" => "I am a full-stack developer with experience in the travel, consulting, recruiting, and human resources industries. I specialize in technologies with languages such as Java, Kotlin, JavaScript, PHP, and Python.",
        "page_profile__text--2" => "I am an entrepreneur who is passionate about learning more about programming, technology, and science. I have a strong knowledge of interface design, user experience, Adobe Photoshop, corporate identity, and digital marketing.",
        "nav_item__home" => "Home",
        "nav_item__about" => "About",
        "nav_item__services" => "Services",
        "nav_item__contact" => "Contact",
        "nav_item__profile" => "Profile",
        "section_summary__title" => "Hello world! Welcome to my professional profile.",
        "section_summary__text--1" => "I am a full-stack developer with experience in the travel, consulting, recruiting, and human resources industries. I specialize in technologies with languages such as Java, Kotlin, JavaScript, PHP, and Python.",
        "section_summary__text--2" => "I am an entrepreneur who is passionate about learning more about programming, technology, and science. I have a strong knowledge of interface design, user experience, Adobe Photoshop, corporate identity, and digital marketing.",
        "section_work__title" => "Work experience",
        "section_education__title" => "Education",
        "section_skills__title" => "Skills",
        "section_soft_skills__title" => "Soft Skills",
        "section_about__title" => "Web development of web applications",
        "section_about__summary" => "I am a web developer with more than 10 years of experience in the development of web applications, I have experience in the development of web applications with PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, among others.",
        "section_about__address" => "Cancún, Quintana Roo, México",
        "section_about__button--contact" => "Contact",
        "section_about__button--profile" => "Profile",
        "section_services__title" => "Services",
        "section_services__item--webapp__title" => "Web Applications",
        "section_services__item--webapp__text--1" => "I develop web applications with the latest technologies, I have experience in the development of web applications with PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, among others.",
        "section_services__item--webapp__text--2" => "I have experience in the development of web applications for different industries such as real estate, restaurants, hotels, travel agencies, among others.",
        "section_services__item--webapp__btn" => "See more about web applications",
        "section_services__item--mobile__title" => "Mobile Applications",
        "section_services__item--mobile__text--1" => "I develop mobile applications with the latest technologies, I have experience in the development of mobile applications with React Native, Android Studio, Java, Kotlin, Swift, among others.",
        "section_services__item--mobile__text--2" => "Mobile applications are a very important part of any business; Since it allows you to reach more customers, I have experience in the development of mobile applications for Android and iOS.",
        "section_services__item--mobile__btn" => "See more about mobile applications",
        "section_services__item--ecommerce__title" => "E-commerce",
        "section_services__item--ecommerce__text--1" => "I develop e-commerce with the latest technologies, I have experience in the development of email marketing campaigns with Mailchimp, Sendgrid, among others.",
        "section_services__item--ecommerce__text--2" => "E-commerce is a very important part of any business, since it allows you to sell your products or services online, I have experience with the most popular payment gateways like PayPal, Stripe, Conekta, MercadoPago, among others.",
        "section_services__item--ecommerce__btn" => "See more about e-commerce",
        "section_contact__title" => "Contact",
        "section_contact__description" => "If you are interested in my services, you can contact me through the following means:",
        "section_contact__description--help" => "Or you can send me a message to the following contact form:",
        "contact_form__legend" => "Contact form, send me a message and I will contact you as soon as possible",
        "contact_form__field--name" => "Name:",
        "contact_form__field--name__placeholder" => "Enter your full name",
        "contact_form__field--phone" => "Phone:",
        "contact_form__field--phone__placeholder" => "Your phone number",
        "contact_form__field--email" => "Email:",
        "contact_form__field--email__placeholder" => "Your email address",
        "contact_form__field--message" => "Message:",
        "contact_form__field--message__placeholder" => "Feel free to share your message here",
        "contact_form__instructions" => "Please fill out all the required fields of this form, so we can assist you better. Your information is safe with us and will only be used to respond to your inquiry.",
        "contact_form__button--submit" => "Send Message",
        "footer__owner" => "Arturo López - Web Developer",
        "footer__copy" => "&copy; " . date("Y") . " - All rights reserved",
    ],
    "es" => [
        "page__profession" => "Desarrollador Web",
        "page_index__title" => "Desarrollador Web Profesional &amp; Experiencia en Portafolio",
        "page_index__seo-title" => "Arturo López - Desarrollador Web Profesional &amp; Experiencia en Portafolio",
        "page_index__seo-description" => "Soy desarrollador web profesional, tengo experiencia con PHP, Javascript, Java, Python, entre otros.",
        "page_profile__title" => "Arturo López - Desarrollador Web | Perfil Profesional",
        "page_profile__seo-title" => "Arturo López - Desarrollador Web | Perfil Profesional",
        "page_profile__seo-description" => "Mi nombre es Arturo López, soy desarrollador full-stack con experiencia en las industrias de viajes, consultoría, reclutamiento y recursos humanos.",
        "page_profile__text--1" => "Soy desarrollador full-stack con experiencia en las industrias de viajes, consultoría, reclutamiento y recursos humanos. Me especializo en tecnologías con lenguajes como Java, Kotlin, JavaScript, PHP y Python.",
        "page_profile__text--2" => "Soy un emprendedor apasionado por aprender más sobre programación, tecnología y ciencia. Tengo un sólido conocimiento de diseño de interfaces, experiencia de usuario, Adobe Photoshop, identidad corporativa y marketing digital.",
        "nav_item__home" => "Inicio",
        "nav_item__about" => "Sobre mí",
        "nav_item__services" => "Servicios",
        "nav_item__contact" => "Contacto",
        "nav_item__profile" => "Perfil",
        "section_summary__title" => "¡Hola mundo! Bienvenido a mi perfil profesional.",
        "section_summary__text--1" => "Soy desarrollador full-stack con experiencia en las industrias de viajes, consultoría, reclutamiento y recursos humanos. Me especializo en tecnologías con lenguajes como Java, Kotlin, JavaScript, PHP y Python.",
        "section_summary__text--2" => "Soy un emprendedor apasionado por aprender más sobre programación, tecnología y ciencia. Tengo un sólido conocimiento de diseño de interfaces, experiencia de usuario, Adobe Photoshop, identidad corporativa y marketing digital.",
        "section_work__title" => "Experiencia laboral",
        "section_education__title" => "Educación",
        "section_skills__title" => "Habilidades",
        "section_soft_skills__title" => "Habilidades Blandas",
        "section_about__title" => "Desarrollo web de aplicaciones web",
        "section_about__summary" => "Soy desarrollador web con más de 10 años de experiencia en el desarrollo de aplicaciones web, tengo experiencia en el desarrollo de aplicaciones web con PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, entre otros.",
        "section_about__address" => "Cancún, Quintana Roo, México",
        "section_about__button--contact" => "Contacto",
        "section_about__button--profile" => "Perfil",
        "section_services__title" => "Servicios",
        "section_services__item--webapp__title" => "Aplicaciones Web",
        "section_services__item--webapp__text--1" => "Desarrollo aplicaciones web con las últimas tecnologías, tengo experiencia en el desarrollo de aplicaciones web con PHP, Laravel, Javascript, VueJS, ReactJS, NodeJS, MySQL, MongoDB, PostgreSQL, HTML5, CSS3, Bootstrap, entre otros.",
        "section_services__item--webapp__text--2" => "Tengo experiencia en el desarrollo de aplicaciones web para diferentes industrias como inmobiliarias, restaurantes, hoteles, agencias de viajes, entre otros.",
        "section_services__item--webapp__btn" => "Ver más sobre aplicaciones web",
        "section_services__item--mobile__title" => "Aplicaciones Móviles",
        "section_services__item--mobile__text--1" => "Desarrollo aplicaciones móviles con las últimas tecnologías, tengo experiencia en el desarrollo de aplicaciones móviles con React Native, Android Studio, Java, Kotlin, Swift, entre otros.",
        "section_services__item--mobile__text--2" => "Las aplicaciones móviles son una parte muy importante de cualquier negocio; ya que te permite llegar a más clientes, tengo experiencia en el desarrollo de aplicaciones móviles para Android e iOS.",
        "section_services__item--mobile__btn" => "Ver más sobre aplicaciones móviles",
        "section_services__item--ecommerce__title" => "E-commerce",
        "section_services__item--ecommerce__text--1" => "Desarrollo e-commerce con las últimas tecnologías, tengo experiencia en el desarrollo de campañas de email marketing con Mailchimp, Sendgrid, entre otros.",
        "section_services__item--ecommerce__text--2" => "El e-commerce es una parte muy importante de cualquier negocio, ya que te permite vender tus productos o servicios en línea, tengo experiencia con las pasarelas de pago más populares como PayPal, Stripe, Conekta, MercadoPago, entre otros.",
        "section_services__item--ecommerce__btn" => "Ver más sobre e-commerce",
        "section_contact__title" => "Contacto",
        "section_contact__description" => "Si estás interesado en mis servicios, puedes contactarme a través de los siguientes medios:",
        "section_contact__description--help" => "O puedes enviarme un mensaje al siguiente formulario de contacto:",
        "contact_form__legend" => "Formulario de contacto, envíame un mensaje y me pondré en contacto contigo lo antes posible",
        "contact_form__field--name" => "Nombre:",
        "contact_form__field--name__placeholder" => "Ingresa tu nombre completo",
        "contact_form__field--phone" => "Teléfono:",
        "contact_form__field--phone__placeholder" => "Tu número de teléfono",
        "contact_form__field--email" => "Correo electrónico:",
        "contact_form__field--email__placeholder" => "Tu dirección de correo electrónico",
        "contact_form__field--message" => "Mensaje:",
        "contact_form__field--message__placeholder" => "Siéntete libre de compartir tu mensaje aquí",
        "contact_form__instructions" => "Por favor, complete todos los campos requeridos de este formulario, para que podamos atenderle mejor. Su información está segura con nosotros y solo se utilizará para responder a su consulta.",
        "contact_form__button--submit" => "Enviar Mensaje",
        "footer__owner" => "Arturo López - Desarrollador Web",
        "footer__copy" => "&copy; " . date("Y") . " - Todos los derechos reservados",
    ]
];

$works = [
    [
        "title_en" => "Java Software Engineer",
        "title_es" => "Ingeniero de Software Java",
        "company" => "Revenatium",
        "company_url" => "https://revenatium.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2019 - " . date("Y"),
        "description_en" => "Backend development of web applications with Java, Spring Boot. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, among others.",
        "description_es" => "Desarrollo backend de aplicaciones web con Java, Spring Boot. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, entre otros.",
        "technologies" => [
            "Java",
            "Kotlin",
            "Spring Boot",
            "MongoDB",
            "PostgreSQL",
        ],
    ],
    [
        "title_en" => "Software Engineer",
        "title_es" => "Ingeniero de Software",
        "company" => "StarChoice",
        "company_url" => "https://starchoice.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2018 - 2019",
        "description_en" => "Full-stack development of web applications with Grails, jQuery, MySQL, HTML5, CSS3, Bootstrap. Web application for the management of recruitment processes.",
        "description_es" => "Desarrollo full-stack de aplicaciones web con Grails, jQuery, MySQL, HTML5, CSS3, Bootstrap. Aplicación web para la gestión de procesos de reclutamiento.",
        "technologies" => [
            "Grails",
            "Java",
            "MySQL",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Marketing Manager",
        "title_es" => "Gerente de Marketing",
        "company" => "Grupo Argos",
        "company_url" => "https://grupoargos.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2016 - 2019",
        "description_en" => "Development of corporate identity, web design, digital marketing, social media management, and SEO",
        "description_es" => "Desarrollo de identidad corporativa, diseño web, marketing digital, gestión de redes sociales y SEO",
        "technologies" => [
            "Adobe Photoshop",
            "Adobe Illustrator",
            "Adobe Premiere",
            "HTML5",
            "CSS3",
            "Bootstrap",
            "WordPress",
            "SEO",
        ],
    ],
    [
        "title_en" => "Java Software Engineer",
        "title_es" => "Ingeniero de Software Java",
        "company" => "Grupo Argos",
        "company_url" => "https://grupoargos.com.mx",
        "location" => "Cancún, Quintana Roo",
        "date" => "2012 - 2016",
        "description_en" => "Backend development of web applications with Java, Spring Framework, SQL Server, HTML5, CSS3, Bootstrap. Web application for the management of payroll and human resources.",
        "description_es" => "Desarrollo backend de aplicaciones web con Java, Spring Framework, SQL Server, HTML5, CSS3, Bootstrap. Aplicación web para la gestión de nómina y recursos humanos.",
        "technologies" => [
            "Java",
            "Spring Framework",
            "SQL Server",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Java Developer / Webmaster",
        "title_es" => "Desarrollador Java / Webmaster",
        "company" => "Sunset World Hotels & Resorts",
        "company_url" => "https://sunsetworldresorts.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2009 - 2012",
        "description_en" => "Java desktop and web development with Java, Play Framework, Oracle, HTML5, CSS3, Bootstrap. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, among others.",
        "description_es" => "Desarrollo de escritorio y web con Java, Play Framework, Oracle, HTML5, CSS3, Bootstrap. Booking Engine, Marketing Automation, CRM, CMS, Channel Manager, Business Intelligence, API Integration, entre otros.",
        "technologies" => [
            "Java",
            "Play Framework",
            "Oracle",
            "HTML5",
            "CSS3",
            "Bootstrap",
        ],
    ],
    [
        "title_en" => "Php Developer / Technical Support",
        "title_es" => "Desarrollador Php / Soporte Técnico",
        "company" => "Freelance",
        "company_url" => "https://linkedin.com/in/lgzarturo",
        "location" => "Cancún, Quintana Roo",
        "date" => "2005 - 2009",
        "description_en" => "Web design and development for clients. Technical support for computer equipment, installation of operating systems, and software",
        "description_es" => "Diseño y desarrollo web para clientes. Soporte técnico para equipos de cómputo, instalación de sistemas operativos y software",
        "technologies" => [
            "Windows",
            "Linux",
            "Microsoft Office",
            "Adobe Suite",
        ],
    ]
];

$education = [
    [
        "title_en" => "Bachelor of Computer Systems Engineering",
        "title_es" => "Ingeniería en Sistemas Computacionales",
        "school" => "ITCancún",
        "school_url" => "https://www.google.com",
        "location" => "Cancún, Quintana Roo",
        "date" => "2000 - 2005",
        "description_en" => "Web Project Development. Participating in the creation of a customer service portal, reservation management, using Java technologies and programming methodologies.",
        "description_es" => "Desarrollo de Proyecto Web. Participando en la creación de un portal de atención al cliente, gestión de reservas, utilizando tecnologías Java y metodologías de programación.",
    ]
];

$skills = [
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Java",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Kotlin",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Groovy &amp; Grails",
    ],
    [
        "icon" => "tabler-icon-code.svg",
        "title" => "Spring Boot",
    ],
    [
        "icon" => "tabler-icon-file-type-php.svg",
        "title" => "PHP",
    ],
    [
        "icon" => "tabler-icon-file-type-php.svg",
        "title" => "Laravel",
    ],
    [
        "icon" => "tabler-icon-brand-javascript.svg",
        "title" => "JavaScript",
    ],
    [
        "icon" => "tabler-icon-brand-typescript.svg",
        "title" => "Typescript",
    ],
    [
        "icon" => "tabler-icon-brand-python.svg",
        "title" => "Python",
    ],
    [
        "icon" => "tabler-icon-brand-django.svg",
        "title" => "Django",
    ],
];

$soft_skills = [
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Teamwork",
        "title_es" => "Trabajo en equipo",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Leadership",
        "title_es" => "Liderazgo",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Communication",
        "title_es" => "Comunicación",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Problem solving",
        "title_es" => "Resolución de problemas",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Creativity",
        "title_es" => "Creatividad",
    ],
    [
        "icon" => "tabler-icon-clipboard-list.svg",
        "title_en" => "Adaptability",
        "title_es" => "Adaptabilidad",
    ]
];
